# Generated by Django 5.1.5 on 2025-01-23 23:25

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Введите имя пользователя",
                        max_length=50,
                        unique=True,
                        verbose_name="Имя пользователя",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите e-mail пользователя",
                        max_length=254,
                        verbose_name="Email пользователя",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото профиля пользователя",
                        null=True,
                        upload_to="static/images/users/avatars/",
                        verbose_name="Фото профиля пользователя",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Введите номер телефона пользователя",
                        max_length=35,
                        null=True,
                        unique=True,
                        verbose_name="Телефон пользователя",
                    ),
                ),
                (
                    "subscription",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите наличие подписки",
                        verbose_name="Наличие подписки",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_amount",
                    models.PositiveIntegerField(help_text="Введите сумму к оплате"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Введите дату создания счета",
                        verbose_name="Дата создания счета",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="unpaid",
                        help_text="Введите статус оплаты",
                        max_length=100,
                        verbose_name="Статус оплаты",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="Укажите id сессии",
                        max_length=250,
                        verbose_name="id сессии",
                    ),
                ),
                (
                    "payment_link",
                    models.URLField(
                        help_text="Укажите ссылку на оплату",
                        max_length=400,
                        verbose_name="Ссылка на оплату",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Введите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата",
                "verbose_name_plural": "Оплаты",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Введите статус активности подписки",
                        verbose_name="Статус активности подписки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Введите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка на сервис",
                "verbose_name_plural": "Подписки на сервис",
                "ordering": ["user"],
            },
        ),
    ]
