# Generated by Django 5.1.5 on 2025-01-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuyerSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка на контент",
                "verbose_name_plural": "Подписки на контент",
            },
        ),
        migrations.CreateModel(
            name="ContentSubscriptionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_amount",
                    models.PositiveIntegerField(help_text="Введите сумму к оплате"),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Введите дату оплаты",
                        verbose_name="Дата оплаты",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="Укажите id сессии",
                        max_length=250,
                        verbose_name="id сессии",
                    ),
                ),
                (
                    "payment_link",
                    models.URLField(
                        help_text="Укажите ссылку на оплату",
                        max_length=400,
                        verbose_name="Ссылка на оплату",
                    ),
                ),
            ],
            options={
                "verbose_name": "Покупка доступа к записи",
                "verbose_name_plural": "Покупки доступа к записям",
                "ordering": ["payment_date"],
            },
        ),
        migrations.CreateModel(
            name="FreeContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название записи",
                        max_length=150,
                        verbose_name="Название записи",
                    ),
                ),
                (
                    "note_body",
                    models.CharField(
                        blank=True,
                        default="Запись отсутствует",
                        help_text="Введите запись",
                        max_length=2000,
                        null=True,
                        verbose_name="Запись",
                    ),
                ),
                (
                    "video_link",
                    models.URLField(
                        blank=True,
                        help_text="Введите ссылку на видео-материал",
                        max_length=500,
                        null=True,
                        verbose_name="Ссылка на видео-материал",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaidContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название записи",
                        max_length=150,
                        verbose_name="Название записи",
                    ),
                ),
                (
                    "note_body",
                    models.CharField(
                        blank=True,
                        default="Запись отсутствует",
                        help_text="Введите запись",
                        max_length=2000,
                        null=True,
                        verbose_name="Запись",
                    ),
                ),
                (
                    "video_link",
                    models.CharField(
                        blank=True,
                        help_text="Введите ссылку на видео-материал",
                        max_length=500,
                        null=True,
                        verbose_name="Ссылка на видео-материал",
                    ),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Введите цену доступа к записи в рублях",
                        verbose_name="Цена доступа к записи",
                    ),
                ),
            ],
        ),
    ]
