# Generated by Django 5.1.5 on 2025-01-23 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="buyersubscription",
            name="user",
            field=models.ForeignKey(
                help_text="Укажите пользователя",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="contentpayment",
            name="user",
            field=models.ForeignKey(
                help_text="Введите пользователя",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="freecontent",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите пользователя",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="paidcontent",
            name="owner",
            field=models.ForeignKey(
                help_text="Укажите пользователя",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="contentpayment",
            name="paid_content",
            field=models.ForeignKey(
                help_text="Введите оплаченный контент",
                on_delete=django.db.models.deletion.CASCADE,
                to="notes.paidcontent",
                verbose_name="Оплаченный контент",
            ),
        ),
        migrations.AddField(
            model_name="buyersubscription",
            name="content",
            field=models.ManyToManyField(
                help_text="Укажите контент",
                to="notes.paidcontent",
                verbose_name="Контент",
            ),
        ),
    ]
