# Generated by Django 5.1.5 on 2025-01-25 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_remove_freecontent_note_body_freecontent_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="freecontent",
            old_name="owner",
            new_name="user",
        ),
    ]
