# Generated by Django 5.1.5 on 2025-01-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_rename_owner_freecontent_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paidcontent",
            old_name="owner",
            new_name="user",
        ),
    ]
