# Generated by Django 5.1.5 on 2025-01-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_rename_owner_paidcontent_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paidcontent",
            old_name="note_body",
            new_name="body",
        ),
    ]
