# Generated by Django 5.1.5 on 2025-01-29 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_rename_note_body_paidcontent_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyersubscription",
            name="content",
        ),
        migrations.AddField(
            model_name="buyersubscription",
            name="content",
            field=models.ForeignKey(
                default=1,
                help_text="Укажите контент",
                on_delete=django.db.models.deletion.CASCADE,
                to="notes.paidcontent",
                verbose_name="Контент",
            ),
            preserve_default=False,
        ),
    ]
