# Generated by Django 5.1.5 on 2025-01-30 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_remove_buyersubscription_content_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpayment",
            name="status",
            field=models.CharField(
                default="unpaid",
                help_text="Введите статус оплаты",
                max_length=100,
                verbose_name="Статус оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="paidcontent",
            name="body",
            field=models.TextField(
                blank=True, help_text="Введите запись", null=True, verbose_name="Запись"
            ),
        ),
        migrations.AlterField(
            model_name="paidcontent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите пользователя",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="paidcontent",
            name="video_link",
            field=models.URLField(
                blank=True,
                help_text="Введите ссылку на видео-материал",
                max_length=500,
                null=True,
                verbose_name="Ссылка на видео-материал",
            ),
        ),
    ]
